var FORMAT_DATE_TIME = "MM/DD/YYYY h:mm a";
var FORMAT_DATE = "MM/DD/YYYY";
var FORMAT_DATE_BOOTSTRAP_CALENDAR = "mm/dd/yyyy";
var FORMAT_DATE_SELECTED_DATE_CALENDAR = "dddd, MMM D, YYYY";
var FORMAT_TIME = "h:mm a";
var FORMAT_TIME_EVENT = "h:mm A";
var FORMAT_DIP_DATE = 'YYYY/MM/DD';

var NOTY_TIME_OUT = 5000;
var MAX_IMAGE_SIZE_MB = 5;

var MODULE_TYPE_POOL = "Pool";
var MODULE_TYPE_SPA = "Spa";

var POOL_TYPE_INDOOR = "InDoor";
var POOL_TYPE_OUTDOOR = "OutDoor";
var POOL_TYPE_OTHERS = "Others";

var PASS_TYPE_POOL_PASS = "PoolPass";
var PASS_TYPE_DAYBED = "Daybed";
var PASS_TYPE_CABANA = "Cabana";