var angular_translate_en = {
    HOME: "Home",
    DASHBOARD: "Dashboard",
    REPORT: "Report",
    REPORTS: "Reports",
    USERS: "Users",
    EVENT_RESERVATIONS: "Event Reservations",
    HOTEL_RESERVATIONS: "Hotel Reservations",
    PROPERTIES: "Properties",
    HOTELS: "Hotels",
    ALL_HOTELS: "All",
    SUBMISSION_HOTELS: "Submission statuses",
    INITIAL_HOTELS: "Initial",
    ON_AIR_HOTELS: "On air",
    SETTINGS: "Settings",
    PROPERTY_PROFILE: "Property Profile",
    RESERVATIONS: "Reservations",
    CALENDAR: "Calendar",
    MESSAGES: "Messages",

    ONLINE: "Online",
    SEARCH: "Search...",
    HEADER: "HEADER",

    YOU_HAVE_MESSAGES: "You have {{ number }} messages",
    SEE_ALL_MESSAGES: "See All Messages",
    YOU_HAVE_NOTIFICATIONS: "You have {{ number }} notifications",
    VIEW_ALL: "View all",
    YOU_HAVE_TASKS: "You have {{ number }} tasks",
    VIEW_ALL_TASKS: "View all tasks",
    MEMBER_SINCE: "Member since {{ date }}",
    FOLLOWERS: "Followers",
    SALES: "Sales",
    FRIENDS: "Friends",
    PROFILE: "Profile",
    SIGN_OUT: "Sign out",

    DIP_ADMIN: "DIP Admin",
    DIP_PARTNER: "DIP Partner",
    DIP_USER: "DIP User",

    FOOTER_RIGHT: "DIP Admin",
    FOOTER_COPYRIGHT: "Copyright &copy; 2016",
    FOOTER_COPYRIGHT_HREF: "DIP",
    FOOTER_ALL_RIGHTS_RESERVED: "All rights reserved.",

    RECENT_ACTIVITY: "Recent Activity",
    TASKS_PROGRESS: "Tasks Progress",
    GENERAL_SETTINGS: "General Settings",

    EXPORT_DATA: "Export Data",
    USERS_REPORT: "Users Report",
    LIST_USERS: "Users List",
    EMAIL: "Email",
    NAME: "Name",
    BIRTHDAY: "Birthday",
    MEMBERSHIP: "Membership",
    SIGN_UP_DATE: "Sign Up Date",
    PHONE: "Phone",

    HOTEL_RESERVATIONS_REPORT: "Hotel Reservations Report",
    LIST_HOTEL_RESERVATIONS: "Hotel Reservations List",
    HOTEL: "Hotel",
    PASS_DATE: "Pass Date",
    PASSES: "Passes",
    BEFORE_TAX: "Before Tax",
    SUB_TOTAL: "Sub Total",
    TAX: "Tax",
    TOTAL: "Total",
    PURCHASED_DATE: "Purchase Date",
    PURCHASE_DETAILS: "Purchase Details",

    EVENT_RESERVATIONS_REPORT: "Event Reservations Report",
    LIST_EVENT_RESERVATIONS: "List Event Reservations",
    HOST: "Hotel",
    EVENT: "Event",
    EVENT_TIME: "Event Time",
    COUNT: "Count",
    QUANTITY: "Quantity",
    PRICE: "Price",


    CREATE_NEW: "Create New",
    ADD: "Add",
    SAVE: "Save",
    CANCEL: "Cancel",
    DELETE: "Delete",
    EDIT: "Edit",
    CHANGE: "Change",
    SUBMIT: "Submit",
    APPROVE: "Approve",
    DECLINE: "Decline",
    DETAILS: "Details",
    SEE_DETAILS: "See details",
    UPLOAD: "Upload",
    NEW_HOTEL: "New Hotel",
    NEXT: "Next",
    PREVIOUS: "Previous",
    GO_BACK: "Go back",
    BACK: "Back",

    CREATE_HOTEL: "Create Hotel",
    EDIT_HOTEL: "Edit Hotel",
    HOTEL_NAME: "Hotel Name",
    ADDRESS: "Address",
    STATE: "State",
    STREET: "Street",
    ZIP_CODE: "Zip Code",
    LOCATION: "Location",
    FRONT_DESK: "Front Desk",
    ROOM_SERVICE: "Room Service",
    WEBSITE: "Website",
    INSTAGRAM: "Instagram Handle",
    CITY: "City",
    NEIGHBORHOOD: "Neighborhood",
    HOTEL_DIP_LOCATION: "Location",
    PROFILE_PICTURE: "Profile picture",
    SELECT_LOCATION: "Select location",
    SELECT_STATE: "Select state",
    DECLINED_REASON: "Declined reason",

    PENDING_HOTEL_NAME: "Pending Hotel Name",
    PENDING_ADDRESS: "Pending Address",
    PENDING_STATE: "Pending State",
    PENDING_STREET: "Pending Street",
    PENDING_ZIP_CODE: "Pending Zip Code",
    PENDING_LOCATION: "Pending Location",
    PENDING_FRONT_DESK: "Pending Front Desk",
    PENDING_ROOM_SERVICE: "Pending Room Service",
    PENDING_WEBSITE: "Pending Website",
    PENDING_INSTAGRAM: "Pending Instagram Handle",
    PENDING_CITY: "Pending City",
    PENDING_NEIGHBORHOOD: "Pending Neighborhood",
    PENDING_HOTEL_DIP_LOCATION: "Pending Location",
    PENDING_PROFILE_PICTURE: "Pending Profile picture",

    APPROVED_HOTEL_NAME: "Approved Hotel Name",
    APPROVED_ADDRESS: "Approved Address",
    APPROVED_STATE: "Approved State",
    APPROVED_STREET: "Approved Street",
    APPROVED_ZIP_CODE: "Approved Zip Code",
    APPROVED_LOCATION: "Approved Location",
    APPROVED_FRONT_DESK: "Approved Front Desk",
    APPROVED_ROOM_SERVICE: "Approved Room Service",
    APPROVED_WEBSITE: "Approved Website",
    APPROVED_INSTAGRAM: "Approved Instagram Handle",
    APPROVED_CITY: "Approved City",
    APPROVED_NEIGHBORHOOD: "Approved Neighborhood",
    APPROVED_HOTEL_DIP_LOCATION: "Approved Location",
    APPROVED_PROFILE_PICTURE: "Approved Profile picture",

    LIST_HOTELS: "Hotel List",
    LIST_ALL_HOTELS: "All Hotels" ,
    LIST_SUBMISSION_HOTELS: "Submission Hotels",
    LIST_INITIAL_HOTELS: "Initial Hotels",
    LIST_ON_AIR_HOTELS: "On Air Hotels",

    HOTEL_DELETE_CONFIRM: "Do you want to delete hotel {{ name }} ?",
    ERROR_MAX_FILE_SIZE: "Allowed file size exceeded. (Max. {{ number }} MB)",
    ERROR_INVALID_HOTEL_PICTURE: "Invalid hotel profile picture",
    CLICK_TO_UPLOAD_PICTURE: "Click here to upload the profile picture",
    CLICK_TO_CHANGE_PICTURE: "Click here to change the profile picture",
    HOTEL_APPROVE_CONFIRM: "Do you want to approve hotel {{ name }} ?",
    HOTEL_UNAPPROVE_CONFIRM: "Do you want to decline hotel {{ name }} ?",
    HOTEL_SUBMIT_CONFIRM: "Do you want to submit hotel {{ name }} ?",
    HOTEL_BOX_PROMPT: "This is your hotel profile. The information you enter here will appear on the app.",

    ERROR_INVALID_URL: "Invalid url",
    ERROR_INVALID_INSTAGRAM: "Instagram handle must like @username or #hashtag",

    HOTEL_PROFILE: "Hotel Profile",
    HOTEL_INFO: "Hotel Info",
    NEW_MODULE: "New Swimming Pool",

    CREATE_MODULE: "New Swimming Pool",
    ADD_MODULE: "Add Amenity",
    MODULE_NAME: "Pool Name",
    TITLE: "Title",
    TYPE: "Type",
    AMENITY_TYPE: "Amenity Type",
    SELECT_TYPE: "Select Type",
    IN_DOOR: "In Door",
    OUT_DOOR: "Out Door",
    OTHERS: "Others",
    LIST_MODULES: "List Swimming Pools",
    SWIMMING_POOL: "Swimming Pool",
    DESCRIPTION_TAG: "Description Tags",
    MODULE_TYPE_POOL: "Swimming Pool",
    MODULE_TYPE_SPA: "Spa",
    MODULE_TYPE_SALON: "Salon",
    MODULE_TYPE_CONFERENCE_CENTER: "Conference Center",
    MODULE_TYPE_GYM: "Gym",
    MODULE_TYPE_HOTEL_ROOM: "Hotel Room",
    SHOW_AMENITY_DETAILS: "Amenity Details",
    HIDE_AMENITY_DETAILS: "Hide Details",
    AMENITY_NO_PASS: "There is no passes on this amenity",
    HOTEL_NO_AMENITY: "There is no amenity on this hotel. Please create a new one",
    TAGGINGLABEL: '(new tag)',

    ERROR_INVALID_HOTEL_SERVICE_PICTURE: "Invalid amenity picture",
    MODULE_DELETE_CONFIRM: "Do you want to delete amenity {{ name }} ?",

    ADD_PASSES: "Add Passes",
    ADD_PASS: "Add Pass",
    CANCEL_ADD_PASS: "Cancel Adding Pass",
    HIDE_ADD_PASS: "Hide Form",
    PASS: "Pass",
    PASS_TYPE: "Pass Type",
    PASS_TITLE: "Pass Name",
    POOL_TITLE: "Pool Name",
    TIME_PERIOD: "Time Period",
    MAXIMUM_PASSES: "Maximum Passes",
    CAPACITY: "Capacity",
    DURATION_START: "Start",
    DURATION_END: "End",
    SHOW_PASS_DETAILS: "Pass Details",
    HIDE_PASS_DETAILS: "Hide Details",

    PASS_TYPE_POOL_PASS: "Pool Pass",
    PASS_TYPE_DAYBED: "Daybed",
    PASS_TYPE_CABANA: "Cabana",

    ERROR_INVALID_PASS_TYPE: "Invalid pass type",
    ERROR_INVALID_PASS_TITLE: "Invalid pass name",
    ERROR_INVALID_PASS_DURATION_START_TIME: "Invalid start time",
    ERROR_INVALID_PASS_DURATION_END_TIME: "Invalid end time",
    ERROR_INVALID_PASS_CAPACITY: "Invalid capacity",
    ERROR_INVALID_PASS_MAXIMUM: "Invalid maximum passes",
    ERROR_INVALID_PASS_PRICE: "Invalid price",
    ERROR_INVALID_PASS_DURATION: "Start time must be smaller than end time",
    ERROR_INVALID_PASS_START_DAY_DUE_DATE: "Start date must be smaller than due day",

    ADD_PASS_SUCCESS_PROMPT: "Your pass is added successfully. Click the calendar to proceed with mapping it",

    PASS_DELETE_CONFIRM: "Do you want to delete pass {{ name }} ?",

    MAP_PASS_TO_CALENDAR: "Map pass to calendar",
    BACK_TO_LIST_VIEW: "Back to list view",

    WEEK_DAY_MONDAY: "Mon",
    WEEK_DAY_TUESDAY: "Tue",
    WEEK_DAY_WEDNESDAY: "Wed",
    WEEK_DAY_THURSDAY: "Thu",
    WEEK_DAY_FRIDAY: "Fri",
    WEEK_DAY_SATURDAY: "Sat",
    WEEK_DAY_SUNDAY: "Sun",

    WEEK_DAY_MONDAY_FULL: "Monday",
    WEEK_DAY_TUESDAY_FULL: "Tuesday",
    WEEK_DAY_WEDNESDAY_FULL: "Wednesday",
    WEEK_DAY_THURSDAY_FULL: "Thursday",
    WEEK_DAY_FRIDAY_FULL: "Friday",
    WEEK_DAY_SATURDAY_FULL: "Saturday",
    WEEK_DAY_SUNDAY_FULL: "Sunday",

    FROM: "From",
    TO: "To",

    CLICK_TO_SET_DETAILS_FOR_PASS: "Click here to set details<br/>for the pass",

    LOGIN: "Login",
    REGISTER: "Register",
    REGISTER_NEW_DIP_PARTNER: "Register a new DIP Partner",
    FULL_NAME: "Full name",
    PASSWORD: "Password",
    CONFIRM_PASSWORD: "Confirm password",
    AGREE_TERMS_BEGIN: "I agree to the ",
    TERMS: "Terms of Service",
    AGREE_TERMS_END: "",
    ALREADY_DIP_PARTNER: "I'm already a DIP Partner",

    ERROR_INVALID_EMAIL: "Invalid email",
    ERROR_PASSWORD_NOT_MATCH: "Whoops, password and confirm password don't match",
    ERROR_INVALID_PASSWORD: "Your password must contain 6 or more characters and at least 1 digit included",
    ERROR_MUST_ACCEPT_TERM: "You must agree to the terms",
    ERROR_INVALID_PHONE_NUMBER: "Invalid phone number",
    ERROR_EXISTING_PASSWORD: "Existing password. Please enter a different one to change your password",
    ERROR_INPUT_REQUIRED: "Please fill out this field",

    SIGN_IN_HEADER: "Sign in to start your session",
    REMEMBER_ME: "Remember Me",
    SIGN_IN: "Sign in",
    FORGOT_PASSWORD: "I forgot my password",
    REGISTER_NEW_MEMBERSHIP: "Register a new DIP Partner",

    RESET_PASSWORD: "Reset Password",
    SEND: "Send",
    RESET_PASSWORD_CHECK_EMAIL: "Please check your email for instructions to reset your password",
    RESET_PASSWORD_SUCCESSFULLY: "Your password was updated",
    TOKEN: "Token",
    VERIFICATION_CODE: "Verification code",
    NEW_PASSWORD: "New Password",
    RESET: "Reset",
    ALREADY_HAS_TOKEN: "I already had reset password verification code",

    CHANGE_PASSWORD: "Change Password",

    UNAUTHORIZED: "Unauthorized",

    HOTEL_ON_AIR: "On Air",
    HOTEL_OFF_AIR: "Off Air",
    HOTEL_STATUS_INITIAL: "Initial",
    HOTEL_STATUS_PENDING: "Pending",
    HOTEL_STATUS_APPROVED: "Approved",
    HOTEL_STATUS_DECLINED: "Declined",
    HOTEL_STATUS_ALL: "All Statuses",
    HOTEL_STATUS: "Status",

    TOGGLE_TO_APPROVE: "Toggle to approve hotel",
    TOGGLE_TO_UNAPPROVE: "Toggle to decline hotel",
    ERROR_HOTEL_NEED_LOCATION_BEFORE_APPROVE: "Please set location for hotel before approve",
    ERROR_HOTEL_NEED_LOCATION_BEFORE_SUBMIT: "Please set location for hotel before submit",
    CONFIRM_PROVIDE_REASON_FOR_DECLINING_HOTEL: "Please provide a reason for declining this hotel"
};