var angular_translate_en = {
    HOME: "Home",
    DASHBOARD: "Dashboard",
    REPORT: "Report",
    USERS: "Users",
    EVENT_RESERVATIONS: "Event Reservations",
    HOTEL_RESERVATIONS: "Hotel Reservations",
    PROPERTIES: "Properties",
    HOTELS: "Hotels",
    SETTINGS: "Settings",

    ONLINE: "Online",
    SEARCH: "Search...",
    HEADER: "HEADER",

    YOU_HAVE_MESSAGES: "You have {{ number }} messages",
    SEE_ALL_MESSAGES: "See All Messages",
    YOU_HAVE_NOTIFICATIONS: "You have {{ number }} notifications",
    VIEW_ALL: "View all",
    YOU_HAVE_TASKS: "You have {{ number }} tasks",
    VIEW_ALL_TASKS: "View all tasks",
    MEMBER_SINCE: "Member since {{ date }}",
    FOLLOWERS: "Followers",
    SALES: "Sales",
    FRIENDS: "Friends",
    PROFILE: "Profile",
    SIGN_OUT: "Sign out",

    FOOTER_RIGHT: "DIP Admin",
    FOOTER_COPYRIGHT: "Copyright &copy; 2016",
    FOOTER_COPYRIGHT_HREF: "DIP",
    FOOTER_ALL_RIGHTS_RESERVED: "All rights reserved.",

    RECENT_ACTIVITY: "Recent Activity",
    TASKS_PROGRESS: "Tasks Progress",
    GENERAL_SETTINGS: "General Settings",

    EXPORT_DATA: "Export Data",
    USERS_REPORT: "Users Report",
    LIST_USERS: "List Users",
    EMAIL: "Email",
    NAME: "Name",
    BIRTHDAY: "Birthday",
    MEMBERSHIP: "Membership",
    SIGN_UP_DATE: "Sign Up Date",

    HOTEL_RESERVATIONS_REPORT: "Hotel Reservations Report",
    LIST_HOTEL_RESERVATIONS: "List Hotel Reservations",
    HOTEL: "Hotel",
    PASS_DATE: "Pass Date",
    PASSES: "Passes",
    BEFORE_TAX: "Before Tax",
    TAX: "Tax",
    TOTAL: "Total",
    PURCHASED_DATE: "Purchased Date",

    EVENT_RESERVATIONS_REPORT: "Event Reservations Report",
    LIST_EVENT_RESERVATIONS: "List Event Reservations",
    HOST: "Host",
    EVENT: "Event",
    EVENT_TIME: "Event Time",
    COUNT: "Count",
    PRICE: "Price",


    SAVE: "Save",
    CANCEL: "Cancel",
    DELETE: "Delete",
    EDIT: "Edit",
    DETAILS: "Details",
    UPLOAD: "Upload",
    NEW_HOTEL: "New Hotel",
    NEXT: "Next",
    PREVIOUS: "Previous",

    CREATE_HOTEL: "Create Hotel",
    EDIT_HOTEL: "Edit Hotel",
    HOTEL_NAME: "Hotel Name",
    ADDRESS: "Address",
    LOCATION: "Location",
    FRONT_DESK: "Front Desk",
    ROOM_SERVICE: "Room Service",
    WEBSITE: "Website",
    INSTAGRAM: "Instagram Handle",
    CITY: "City",
    NEIGHBORHOOD: "Neighborhood",
    PROFILE_PICTURE: "Profile picture",

    LIST_HOTELS: "List Hotels",

    HOTEL_DELETE_CONFIRM: "Do you want to delete hotel {{ name }} ?",
    ERROR_MAX_FILE_SIZE: "Allowed file size exceeded. (Max. {{ number }} MB)",
    ERROR_INVALID_HOTEL_PICTURE: "Invalid hotel profile picture",

    HOTEL_PROFILE: "Hotel Profile",
    HOTEL_INFO: "Hotel Info",
    NEW_MODULE: "New Swimming Pool",

    CREATE_MODULE: "Create Swimming Pool",
    MODULE_NAME: "Pool Name",
    TYPE: "Type",
    IN_DOOR: "In Door",
    OUT_DOOR: "Out Door",
    OTHERS: "Others",
    LIST_MODULES: "List Swimming Pools",

    ERROR_INVALID_HOTEL_SERVICE_PICTURE: "Invalid swimming pool picture",
    MODULE_DELETE_CONFIRM: "Do you want to delete pool {{ name }} ?",

    ADD_PASSES: "Add Passes",
    PASS: "Pass",
    PASS_TYPE: "Pass Type",
    PASS_TITLE: "Pass Title",
    POOL_TITLE: "Pool Title",
    TIME_PERIOD: "Time Period",
    MAXIMUM_PASSES: "Maximum Passes",
    CAPACITY: "Capacity",
    DURATION_START: "Start",
    DURATION_END: "End",

    PASS_TYPE_POOL_PASS: "Pool Pass",
    PASS_TYPE_DAYBED: "Daybed",
    PASS_TYPE_CABANA: "Cabana",

    ERROR_INVALID_PASS_TYPE: "Invalid pass type",
    ERROR_INVALID_PASS_TITLE: "Invalid pass title",
    ERROR_INVALID_PASS_DURATION_START_TIME: "Invalid start time",
    ERROR_INVALID_PASS_DURATION_END_TIME: "Invalid end time",
    ERROR_INVALID_PASS_CAPACITY: "Invalid capacity",
    ERROR_INVALID_PASS_MAXIMUM: "Invalid maximum passes",
    ERROR_INVALID_PASS_PRICE: "Invalid price",
    ERROR_INVALID_PASS_DURATION: "Start time must be smaller than end time"
};