var angular_translate_en = {
    HOME: "Home",
    DASHBOARD: "Dashboard",
    REPORT: "Report",
    USERS: "Users",
    EVENT_RESERVATIONS: "Event Reservations",
    HOTEL_RESERVATIONS: "Hotel Reservations",
    PROPERTIES: "Properties",
    HOTELS: "Hotels",
    SETTINGS: "Settings",

    ONLINE: "Online",
    SEARCH: "Search...",
    HEADER: "HEADER",

    YOU_HAVE_MESSAGES: "You have {{ number }} messages",
    SEE_ALL_MESSAGES: "See All Messages",
    YOU_HAVE_NOTIFICATIONS: "You have {{ number }} notifications",
    VIEW_ALL: "View all",
    YOU_HAVE_TASKS: "You have {{ number }} tasks",
    VIEW_ALL_TASKS: "View all tasks",
    MEMBER_SINCE: "Member since {{ date }}",
    FOLLOWERS: "Followers",
    SALES: "Sales",
    FRIENDS: "Friends",
    PROFILE: "Profile",
    SIGN_OUT: "Sign out",

    FOOTER_RIGHT: "DIP Admin",
    FOOTER_COPYRIGHT: "Copyright &copy; 2016",
    FOOTER_COPYRIGHT_HREF: "DIP",
    FOOTER_ALL_RIGHTS_RESERVED: "All rights reserved.",

    RECENT_ACTIVITY: "Recent Activity",
    TASKS_PROGRESS: "Tasks Progress",
    GENERAL_SETTINGS: "General Settings",

    EXPORT_DATA: "Export Data",
    USERS_REPORT: "Users Report",
    LIST_USERS: "Users List",
    EMAIL: "Email",
    NAME: "Name",
    BIRTHDAY: "Birthday",
    MEMBERSHIP: "Membership",
    SIGN_UP_DATE: "Sign Up Date",

    HOTEL_RESERVATIONS_REPORT: "Hotel Reservations Report",
    LIST_HOTEL_RESERVATIONS: "Hotel Reservations List",
    HOTEL: "Hotel",
    PASS_DATE: "Pass Date",
    PASSES: "Passes",
    BEFORE_TAX: "Before Tax",
    TAX: "Tax",
    TOTAL: "Total",
    PURCHASED_DATE: "Purchased Date",

    EVENT_RESERVATIONS_REPORT: "Event Reservations Report",
    LIST_EVENT_RESERVATIONS: "List Event Reservations",
    HOST: "Hotel",
    EVENT: "Event",
    EVENT_TIME: "Event Time",
    COUNT: "Quantity",
    PRICE: "Price",


    CREATE_NEW: "Create New",
    SAVE: "Save",
    CANCEL: "Cancel",
    DELETE: "Delete",
    EDIT: "Edit",
    DETAILS: "Details",
    UPLOAD: "Upload",
    NEW_HOTEL: "New Hotel",
    NEXT: "Next",
    PREVIOUS: "Previous",
    GO_BACK: "Go back",
    BACK: "Back",

    CREATE_HOTEL: "Create Hotel",
    EDIT_HOTEL: "Edit Hotel",
    HOTEL_NAME: "Hotel Name",
    ADDRESS: "Address",
    LOCATION: "Location",
    FRONT_DESK: "Front Desk",
    ROOM_SERVICE: "Room Service",
    WEBSITE: "Website",
    INSTAGRAM: "Instagram Handle",
    CITY: "City",
    NEIGHBORHOOD: "Neighborhood",
    PROFILE_PICTURE: "Profile picture",

    LIST_HOTELS: "Hotels List",

    HOTEL_DELETE_CONFIRM: "Do you want to delete hotel {{ name }} ?",
    ERROR_MAX_FILE_SIZE: "Allowed file size exceeded. (Max. {{ number }} MB)",
    ERROR_INVALID_HOTEL_PICTURE: "Invalid hotel profile picture",
    CLICK_TO_UPLOAD_PICTURE: "Click here to upload the profile picture",
    CLICK_TO_CHANGE_PICTURE: "Click here to change the profile picture",

    HOTEL_PROFILE: "Hotel Profile",
    HOTEL_INFO: "Hotel Info",
    NEW_MODULE: "New Swimming Pool",

    CREATE_MODULE: "New Swimming Pool",
    MODULE_NAME: "Pool Name",
    TYPE: "Type",
    IN_DOOR: "In Door",
    OUT_DOOR: "Out Door",
    OTHERS: "Others",
    LIST_MODULES: "List Swimming Pools",

    ERROR_INVALID_HOTEL_SERVICE_PICTURE: "Invalid swimming pool picture",
    MODULE_DELETE_CONFIRM: "Do you want to delete pool {{ name }} ?",

    ADD_PASSES: "Add Passes",
    ADD_PASS: "Add Pass",
    PASS: "Pass",
    PASS_TYPE: "Pass Type",
    PASS_TITLE: "Pass Name",
    POOL_TITLE: "Pool Name",
    TIME_PERIOD: "Time Period",
    MAXIMUM_PASSES: "Maximum Passes",
    CAPACITY: "Capacity",
    DURATION_START: "Start",
    DURATION_END: "End",

    PASS_TYPE_POOL_PASS: "Pool Pass",
    PASS_TYPE_DAYBED: "Daybed",
    PASS_TYPE_CABANA: "Cabana",

    ERROR_INVALID_PASS_TYPE: "Invalid pass type",
    ERROR_INVALID_PASS_TITLE: "Invalid pass name",
    ERROR_INVALID_PASS_DURATION_START_TIME: "Invalid start time",
    ERROR_INVALID_PASS_DURATION_END_TIME: "Invalid end time",
    ERROR_INVALID_PASS_CAPACITY: "Invalid capacity",
    ERROR_INVALID_PASS_MAXIMUM: "Invalid maximum passes",
    ERROR_INVALID_PASS_PRICE: "Invalid price",
    ERROR_INVALID_PASS_DURATION: "Start time must be smaller than end time",
    ERROR_INVALID_PASS_START_DAY_DUE_DATE: "Start date must be smaller than due day",

    PASS_DELETE_CONFIRM: "Do you want to delete pass {{ name }} ?",

    MAP_PASS_TO_CALENDAR: "Map pass to calendar",
    BACK_TO_LIST_VIEW: "Back to list view",

    WEEK_DAY_MONDAY: "Mon",
    WEEK_DAY_TUESDAY: "Tue",
    WEEK_DAY_WEDNESDAY: "Wed",
    WEEK_DAY_THURSDAY: "Thu",
    WEEK_DAY_FRIDAY: "Fri",
    WEEK_DAY_SATURDAY: "Sat",
    WEEK_DAY_SUNDAY: "Sun",

    WEEK_DAY_MONDAY_FULL: "Monday",
    WEEK_DAY_TUESDAY_FULL: "Tuesday",
    WEEK_DAY_WEDNESDAY_FULL: "Wednesday",
    WEEK_DAY_THURSDAY_FULL: "Thursday",
    WEEK_DAY_FRIDAY_FULL: "Friday",
    WEEK_DAY_SATURDAY_FULL: "Saturday",
    WEEK_DAY_SUNDAY_FULL: "Sunday",

    FROM: "From",
    TO: "To",

    CLICK_TO_SET_DETAILS_FOR_PASS: "Click here to set details<br/>for the pass",

    REGISTER: "Register",
    REGISTER_NEW_DIP_PARTNER: "Register a new DIP Partner",
    FULL_NAME: "Full name",
    PASSWORD: "Password",
    CONFIRM_PASSWORD: "Confirm password",
    AGREE_TERMS_BEGIN: "I agree to the ",
    TERMS: "terms",
    AGREE_TERMS_END: "",
    ALREADY_DIP_PARTNER: "I'm already a DIP Partner",

    ERROR_INVALID_EMAIL: "Invalid email",
    ERROR_PASSWORD_NOT_MATCH: "Whoops, password and confirm password don't match",
    ERROR_INVALID_PASSWORD: "Your password must have 6 or more characters, at least 1 digit",

    SIGN_IN_HEADER: "Sign in to start your session",
    REMEMBER_ME: "Remember Me",
    SIGN_IN: "Sign in",
    FORGOT_PASSWORD: "I forgot my password",
    REGISTER_NEW_MEMBERSHIP: "Register a new membership",

    RESET_PASSWORD: "Reset Password",
    SEND: "Send",
    RESET_PASSWORD_CHECK_EMAIL: "Please check your email for instructions to reset your password",
    RESET_PASSWORD_SUCCESSFULLY: "Your password was updated",
    TOKEN: "Token",
    NEW_PASSWORD: "New Password",
    RESET: "Reset",
    ALREADY_HAS_TOKEN: "I already had reset password token"
};