module.exports = {
    HOTELS_UNLOCKED: "Hotels Unlocked",
    ACCESS_HOTEL: "Access hotel swimming pools & spas",
    AMENITIES_ON_DEMAND: "Amenities On Demand",
    EXPERIENCE_FINGERTIPS: "Experience at your fingertips",
    WELCOME_TO_DIP: "Welcome to Dip",
    WHAT_ARE_YOU_WAITING_FOR: "What are you waiting for?",
    LOG_IN: "Log In",
    SIGN_UP: "Sign Up",
    CREATE_ACCOUNT: "Create Account",
    CONNECT_WITH_FACEBOOK: "Connect with Facebook",
    SIGN_UP_WITH_EMAIL: "Sign up with email",
    LOGIN_WITH_EMAIL: "Log in with email",
    BY_SIGNING_UP_AGREE: "By signing up, I agree to Dip's",
    TERM_OF_SERVICE: "Term of Service",
    PRIVACY_POLICY: "Privacy Policy",
    AND: "and",
    OR: "or",
    EMAIL: "Email",
    PASSWORD: "Password",
    FORGOT_PASSWORD: "Forgot Password",
    FULL_NAME: "Full Name",
    PASSWORD_MUST_HAVE: "Your password must have:",
    PASSWORD_MORE_CHARACTERS: "6 or more characters.",
    PASSWORD_AT_LEAST_DIGIT: "At least 1 digit.",
    RESET_PASSWORD: "Reset Password",
    SEND: "Send",
    RESET: "Reset",
    VERIFICATION_CODE: "Verification Code",
    NEW_PASSWORD: "New Password",
    CONFIRM_PASSWORD: "Confirm Password",
    RESET_PASSWORD_CHECK_EMAIL: "Please check your email for instructions to reset your password",
    OK: 'OK',
    ERROR: 'Error',
    INPUT: 'Input',
    LOGIN_ERROR_ENTER_ALL_FIELDS: 'Please enter your info to all fields to login.',
    EMPTY_EMAIL: 'Empty Email',
    RESET_PASSWORD_ERROR_ENTER_EMAIL: 'Please enter your email address.',
    RESET_PASSWORD_ERROR_ENTER_ALL_FIELDS: 'Please enter your info to all fields to continue.',
    MISMATCHED_PASSWORD: 'Mismatched Password',
    RESET_PASSWORD_ERROR_PASSWORD_NOT_MATCH: 'Please double-check to ensure your password is matched.',
};